spring:
  datasource:
    url: jdbc:h2:mem:workloaddb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  activemq:
    broker-url: tcp://localhost:61616
  jms:
    pub-sub-domain: false
    listener:
      min-concurrency: 2
      max-concurrency: 5

app:
  messaging:
    training:
      queue: training.events
      dlq: training.events.dlq
      max-redeliveries: 3
