spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gymcrm_local
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  activemq:
    broker-url: tcp://localhost:61616
  jms:
    pub-sub-domain: false
    listener:
      min-concurrency: 2
      max-concurrency: 5
  data:
    mongodb:
      host: localhost
      port: 27017
      database: gymcrm_local

app:
  messaging:
    training:
      queue: training.events
      dlq: training.events.dlq
      max-redeliveries: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info
