spring:
  application:
    name: integration-tests

  data:
    mongodb:
      uri: placeholder

  activemq:
    broker-url: placeholder
jwt:
  secret: "6b6LZpM24yEnN0uYFi1tBpKoYkeP3vM8"

eureka:
  client:
    enabled: false
